---
title: "HW0410"
author: "Tianjian Xie"
date: "2023-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(hrbrthemes)
library(dplyr)
library(EnvStats)
```

##Problem18.78:
```{r}
Area <- rep(c(1:19),2)
`2001` <- c(4.7,4.1,3.9,5.0,5.0,4.3,4.4,5.6,5.3,6.3,2.6,5.2,2.6,3.2,4.6,3.5,4.6,4.1,5.6)
`2002` <- c(6.0,4.0,4.1,5.3,5.6,5.2,5.6,6.9,7.2,8.7,2.3,5.2,2.9,3.7,5.5,4.6,5.8,5.9,7.7)
rate <- c(`2001`,`2002`)
Year <- c(rep(as.integer(2001),19),rep(as.integer(2002),19))
df18.78 <- data.frame(Area,rate,Year)
plot18.78 <- ggplot(df18.78,aes(x=Area,y=rate,color=Year)) +
    geom_point(size=6)
plot18.78
```

```{r}
group_by(df18.78,Year) %>%
  summarise(count = n(),
            mean = mean(rate,na.rm = TRUE),
            sd = sd(rate, na.rm = TRUE)
            )
df18.78_2001 <- subset(df18.78,Year == "2001",rate,drop = TRUE)
df18.78_2002 <- subset(df18.78,Year == "2002",rate,drop = TRUE)
res <- t.test(df18.78_2001,df18.78_2002,paired = TRUE)
res
pertest <- twoSamplePermutationTestLocation(df18.78_2001,df18.78_2002)
pertest
```